### ISSUE TITLE
Previous efforts

### ISSUE THREAD

**Issue by timj** [telegraphic/fits2hdf#1]
Just in case this information is not known to you, the Starlink project has a data format that is very similar to HDF5 (called HDS) and they wrote a CONVERT application that can convert FITS files to this hierarchical format. This might give you some pointers although the complications are mainly associated with round-tripping (so going from FITS to the hierarchical format and then back to FITS).
- Source code: https://github.com/Starlink/starlink/tree/master/applications/convert
- HDS library rewritten in terms of HDF5 (which very shortly will let the CONVERT application above convert FITS files to HDF5 and back again): https://github.com/timj/hds-on-hdf5

And for a previous attempt at HDF5/FITS interoperability: http://adsabs.harvard.edu/abs/1995ASPC...77..229J

**Comment by telegraphic** [comment]
Hi Tim, thanks for the links. Was hoping to get a chance to chat to you at ADASS, but glad we're picking up the conversation here.

Jennings and co were sadly a few years too early (ahead of their time!), and were trying to map FITS -> HDF4. I have no doubt had HDF5 been around the story would be quite different. 

Agreed that round-tripping is what adds the most complexity, if the round-trip file needs to be identical to the input file. I'm tempted to force all files into the MEF-style FITS format, where the PRIMARY HDU is just a header, and data are moved to an extension HDU. The problem is of course legacy, and seeing as I'm trying to support UVFITS (which stores tables in random groups), this is a bit troublesome.

If you've got any prototype NDF data in HDF5 format, please let me know, it'd be fun to play around with. Will then be interesting to compare NDF-HDF5 format to the FITS-HDF5 format. It would be excellent if with a few changes to what I've done here will create datasets that are at a minimum NDF "aware".

And please do keep in touch with your progress! I plan on exploring compression and file I/O in more detail for an A&C paper, so if you're interested in this kind of thing let me know.

Cheers
Danny

PS: If you'd like to take this off-list, my email is dprice _at_ cfa . harvard . edu

**Comment by telegraphic** [comment]
On this front, the [HDFITS Astronomy & Computing paper](http://www.sciencedirect.com/science/article/pii/S2213133715000554) is now available:

```
D.C. Price, B.R. Barsdell, L.J. Greenhill, HDFITS: Porting the FITS data model to HDF5,
Astronomy and Computing, Available online 22 May 2015, ISSN 2213-1337,
http://dx.doi.org/10.1016/j.ascom.2015.05.001.
```

Currently in the accepted but pre-proof stage; it'll be up on arXiv soon too.
